<?php

use Drupal\BehatEditor,
    Drupal\BehatEditorSauceLabs,
    Drupal\BehatRunner;

define('BEHAT_CRON_RUNNER_OFFSET_SECONDS', '3600');

/**
 * @file
 * Setup @critical feature files to run per cron
 */

/**
 * Implements hook_permission().
 *
 * Who can see the tests
 */

function behat_cron_runner_permission() {
    $items['behat cron runner see tests'] = array(
        'title' => t('Can see tests marked @critical'),
        'description' => t('Can see tests marked @critical')
    );
    return $items;
}

/**
 * Implements hook_menu().
 *
 * Show some stats for the jobs
 *
 */

function behat_cron_runner_menu() {
    $path = drupal_get_path('module', 'behat_cron_runner');
    $items['admin/behat/index/critical'] = array(
        'page callback' => 'behat_cron_runner_index',
        'access arguments' => array('behat cron runner see tests'),
        'file' => 'behat_cron_runner_index.inc',
        'file path' => "$path/includes/"
    );

    /**
     * no menu for wormly.html since it is in the files folder
     */

    return $items;
}



/**
 * Implements hook_cron().
 *
 * Check if it is time to run again
 * using behat_cron_runner_offset_seconds()
 *
 * If TRUE trigger the job(s) with behat_cron_runner_foreach_critical_tests()
 */



/**
 * Implements hook_module_enable().
 *
 * Recreate the critical_tests cache
 *
 */


/**
 * Implements hook_module_disable().
 *
 * Recreate the critical_tests cache
 *
 */


/**
 * Extends the File class to add a
 * rebuild on Save file
 */