<?php

use Drupal\BehatEditor,
    Drupal\BehatEditorSauceLabs,
    Drupal\BehatRunner;

define('BEHAT_CRON_RUNNER_OFFSET_SECONDS', '0');

/**
 * @file
 * Setup @critical feature files to run per cron
 */

/**
 * Implements hook_permission().
 *
 * Who can see the tests
 */

function behat_cron_runner_permission() {
    $items['behat cron runner see tests'] = array(
        'title' => t('Can see tests marked @critical'),
        'description' => t('Can see tests marked @critical')
    );
    return $items;
}

/**
 * Implements hook_menu().
 *
 * Show some stats for the jobs
 *
 */

function behat_cron_runner_menu() {
    $path = drupal_get_path('module', 'behat_cron_runner');
    $items['admin/behat/index/critical'] = array(
        'page callback' => 'behat_cron_runner_index',
        'access arguments' => array('behat cron runner see tests'),
        'file' => 'behat_cron_runner_index.inc',
        'file path' => "$path/includes/"
    );

    /**
     * no menu for wormly.html since it is in the files folder
     */

    return $items;
}

function behat_cron_runner_cronapi() {
    $items = array();
    $items['_behat_cron_runner_run'] = array(
        'scheduler' => array(
            'name' => 'crontab',
            'crontab' => array(
                'rules' => array('*/5 * * * *'),
            )
        )
    );
    return $items;
}

/**
 * Group functions to make the final call
 */
function _behat_cron_runner_run() {
    composer_manager_register_autoloader();
    //1. get files
    $root_test_path = variable_get('file_private_path') . '/behat_tests/';
    $getTests = new BehatRunner\GetTests($root_test_path);

    $iterator = $getTests->finder->files()
        ->name('*.feature')
        ->contains('@critical')
        ->in($root_test_path);

    $yml_path = variable_get('file_private_path') . '/behat.yml';
    $bin_path = drupal_realpath(variable_get('composer_manager_vendor_dir')) . '/bin/';
    $runner = new BehatRunner\BehatEditorRun($yml_path, null, $bin_path);

    //2. Iterate over files and run
    $results = $runner->runMany($iterator);

    //3. Build report
    $wormlyReport = new Drupal\BehatRunner\WormlyReport();
    $html = $wormlyReport->createWormlyPages($results);
    $wormlyReport->createManyFiles($html);

    variable_set('behat_cron_runner_last_run', REQUEST_TIME);
}
